version: '3.8'

services:
  DrivingLicenseIssuanceSystem-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=DrivingLicenseIssuanceSystemStrongPassword2025!
    ports:
      - "1434:1433"
    networks:
      - DrivingLicenseIssuanceSystem-net

  DrivingLicenseIssuanceSystem-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=DrivingLicenseIssuanceSystem-db;Database=DrivingLicenseIssuanceSystemDb;User Id=sa;Password=DrivingLicenseIssuanceSystemStrongPassword2025!;TrustServerCertificate=True
    ports:
      - "5000:5000"
    depends_on:
      - DrivingLicenseIssuanceSystem-db
    networks:
      - DrivingLicenseIssuanceSystem-net

  DrivingLicenseIssuanceSystem-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - DrivingLicenseIssuanceSystem-backend
    networks:
      - DrivingLicenseIssuanceSystem-net

networks:
  DrivingLicenseIssuanceSystem-net:
    driver: bridge
