version: '3.8'

services:
  mojaz-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MojazStrongPassword2025!
    ports:
      - "1434:1433"
    networks:
      - mojaz-net

  mojaz-backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mojaz-db;Database=MojazDb;User Id=sa;Password=MojazStrongPassword2025!;TrustServerCertificate=True
    ports:
      - "5000:5000"
    depends_on:
      - mojaz-db
    networks:
      - mojaz-net

  mojaz-frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - mojaz-backend
    networks:
      - mojaz-net

networks:
  mojaz-net:
    driver: bridge
