// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mojaz.Infrastructure.Persistence;

#nullable disable

namespace Mojaz.Infrastructure.Migrations
{
    [DbContext(typeof(MojazDbContext))]
    [Migration("20260425120000_AddMissingApplicationAndAppointmentColumns")]
    partial class AddMissingApplicationAndAppointmentColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Mojaz.Domain.Entities.Application", b =>
                {
                    b.Property<bool?>("AdditionalTrainingRequired")
                        .HasColumnType("bit");

                    b.Property<string>("FinalDecisionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PracticalAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("ReturnToStage")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TheoryAttemptCount")
                        .HasColumnType("int");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Appointment", b =>
                {
                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool?>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<int?>("RescheduleCount")
                        .HasColumnType("int");
                });
#pragma warning restore 612, 618
        }
    }
}