// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mojaz.Infrastructure.Persistence;

#nullable disable

namespace Mojaz.Infrastructure.Migrations
{
    [DbContext(typeof(MojazDbContext))]
    [Migration("20260410141921_AddReplacementReasonDetails")]
    partial class AddReplacementReasonDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mojaz.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdditionalTrainingRequired")
                        .HasColumnType("bit");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DataAccuracyConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalDecision")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinalDecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FinalDecisionBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FinalDecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LicenseCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicenseCategoryId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ManagerNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PracticalAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReturnToStage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<bool>("SpecialNeeds")
                        .HasMaxLength(200)
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TheoryAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("IX_Applications_ApplicantId");

                    b.HasIndex("ApplicantId1");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Applications_ApplicationNumber");

                    b.HasIndex("LicenseCategoryId");

                    b.HasIndex("LicenseCategoryId1");

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DocumentType");

                    b.HasIndex("Status");

                    b.HasIndex("ApplicationId", "DocumentType")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("ApplicationDocuments", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ChangedAt");

                    b.ToTable("ApplicationStatusHistories", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("ReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RescheduleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("AppointmentType");

                    b.HasIndex("BranchId");

                    b.HasIndex("RescheduleCount");

                    b.HasIndex("ScheduledDate");

                    b.HasIndex("Status");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityName");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.CategoryUpgrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpgradedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("UpgradedAt");

                    b.ToTable("CategoryUpgrades", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecipientEmail", "TemplateName", "ReferenceId")
                        .HasDatabaseName("IX_EmailLogs_RecipientEmail_TemplateName_ReferenceId");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.FeeStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LicenseCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LicenseCategoryId");

                    b.HasIndex("FeeType", "LicenseCategoryId", "IsActive");

                    b.ToTable("FeeStructures", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HolderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IssuedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicenseCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("QrCode")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_Licenses_ApplicationId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Licenses_ExpiresAt");

                    b.HasIndex("HolderId")
                        .HasDatabaseName("IX_Licenses_HolderId");

                    b.HasIndex("LicenseCategoryId")
                        .HasDatabaseName("IX_Licenses_LicenseCategoryId");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Licenses_LicenseNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Licenses_Status");

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.LicenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresTraining")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ValidityYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("LicenseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "A",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 882, DateTimeKind.Utc).AddTicks(8663),
                            IsActive = true,
                            MinimumAge = 16,
                            NameAr = "دراجة نارية",
                            NameEn = "Motorcycle",
                            RequiresTraining = true,
                            ValidityYears = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "B",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 882, DateTimeKind.Utc).AddTicks(8685),
                            IsActive = true,
                            MinimumAge = 18,
                            NameAr = "خصوصي",
                            NameEn = "Private",
                            RequiresTraining = true,
                            ValidityYears = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "C",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 882, DateTimeKind.Utc).AddTicks(8689),
                            IsActive = true,
                            MinimumAge = 21,
                            NameAr = "نقل عام",
                            NameEn = "Public Transport",
                            RequiresTraining = true,
                            ValidityYears = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Code = "D",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 882, DateTimeKind.Utc).AddTicks(8693),
                            IsActive = true,
                            MinimumAge = 21,
                            NameAr = "مركبات ثقيلة",
                            NameEn = "Heavy Vehicles",
                            RequiresTraining = true,
                            ValidityYears = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Code = "E",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 882, DateTimeKind.Utc).AddTicks(8696),
                            IsActive = true,
                            MinimumAge = 21,
                            NameAr = "مركبات صناعية",
                            NameEn = "Industrial Vehicles",
                            RequiresTraining = true,
                            ValidityYears = 0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Code = "F",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 882, DateTimeKind.Utc).AddTicks(8699),
                            IsActive = true,
                            MinimumAge = 18,
                            NameAr = "مركبات زراعية",
                            NameEn = "Agricultural Vehicles",
                            RequiresTraining = true,
                            ValidityYears = 0
                        });
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.LicenseRenewal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NewExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RenewedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("RenewedAt");

                    b.ToTable("LicenseRenewals", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.LicenseReplacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsReportVerified")
                        .HasColumnType("bit");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.Property<string>("ReviewComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("LicenseReplacements", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.MedicalExamination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodType")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CertificatePath")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExaminedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FitnessResult")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ReportReference")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FitnessResult");

                    b.ToTable("MedicalExaminations", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("MessageAr")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("MessageEn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_Notifications_ApplicationId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_Notifications_EventType");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_Notifications_SentAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DestinationType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsInvalidated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Destination");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Purpose");

                    b.HasIndex("UserId");

                    b.ToTable("OtpCodes", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasFilter("[TransactionReference] IS NOT NULL");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.PracticalTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AdditionalHoursRequired")
                        .HasColumnType("int");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConductedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExaminerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresAdditionalTraining")
                        .HasColumnType("bit");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleUsed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ExaminerId");

                    b.ToTable("PracticalTests", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.PushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushTokens", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.SmsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TwilioMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_SmsLogs_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SmsLogs_Status");

                    b.HasIndex("UserId", "TemplateType")
                        .HasDatabaseName("IX_SmsLogs_UserId_TemplateType");

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000001001"),
                            Category = "OTP",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9523),
                            Description = "OTP validity in minutes for SMS",
                            IsEncrypted = false,
                            SettingKey = "OTP_VALIDITY_MINUTES_SMS",
                            SettingValue = "5"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000001002"),
                            Category = "OTP",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9630),
                            Description = "OTP validity in minutes for Email",
                            IsEncrypted = false,
                            SettingKey = "OTP_VALIDITY_MINUTES_EMAIL",
                            SettingValue = "10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000001003"),
                            Category = "OTP",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9640),
                            Description = "Max OTP verification attempts",
                            IsEncrypted = false,
                            SettingKey = "OTP_MAX_ATTEMPTS",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000001004"),
                            Category = "OTP",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9643),
                            Description = "Cooldown in seconds before resending OTP",
                            IsEncrypted = false,
                            SettingKey = "OTP_RESEND_COOLDOWN_SECONDS",
                            SettingValue = "60"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000001005"),
                            Category = "OTP",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9652),
                            Description = "Max OTP resends per hour",
                            IsEncrypted = false,
                            SettingKey = "OTP_MAX_RESEND_PER_HOUR",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000007001"),
                            Category = "Email",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9775),
                            Description = "Deduplication window in seconds for outgoing emails",
                            IsEncrypted = false,
                            SettingKey = "EMAIL_DEDUP_WINDOW_SECONDS",
                            SettingValue = "300"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000007002"),
                            Category = "Email",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9779),
                            Description = "Maximum retry attempts for failed emails",
                            IsEncrypted = false,
                            SettingKey = "EMAIL_MAX_RETRIES",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000007003"),
                            Category = "Email",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9783),
                            Description = "Base delay in seconds for email retry exponential backoff",
                            IsEncrypted = false,
                            SettingKey = "EMAIL_RETRY_BASE_DELAY_SECONDS",
                            SettingValue = "60"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008001"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9793),
                            Description = "Maximum number of times an applicant can reschedule an appointment",
                            IsEncrypted = false,
                            SettingKey = "MAX_RESCHEDULE_COUNT",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008002"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9795),
                            Description = "Default duration of an appointment slot in minutes",
                            IsEncrypted = false,
                            SettingKey = "DEFAULT_APPOINTMENT_DURATION_MINUTES",
                            SettingValue = "30"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008003"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9798),
                            Description = "Maximum number of appointments allowed per time slot per branch",
                            IsEncrypted = false,
                            SettingKey = "MAX_APPOINTMENTS_PER_SLOT",
                            SettingValue = "2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008004"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9803),
                            Description = "Buffer time between appointments in minutes",
                            IsEncrypted = false,
                            SettingKey = "SLOT_BUFFER_MINUTES",
                            SettingValue = "15"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008005"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9809),
                            Description = "Start of working hours for appointments (24-hour format)",
                            IsEncrypted = false,
                            SettingKey = "WORKING_HOURS_START",
                            SettingValue = "08:00"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008006"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9815),
                            Description = "End of working hours for appointments (24-hour format)",
                            IsEncrypted = false,
                            SettingKey = "WORKING_HOURS_END",
                            SettingValue = "16:00"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008007"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9818),
                            Description = "Hours before appointment to send reminder notification",
                            IsEncrypted = false,
                            SettingKey = "REMINDER_HOURS_BEFORE",
                            SettingValue = "24"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008008"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9820),
                            Description = "Minimum days in advance an appointment must be booked",
                            IsEncrypted = false,
                            SettingKey = "MIN_BOOKING_DAYS_AHEAD",
                            SettingValue = "1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000008009"),
                            Category = "Appointment",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9836),
                            Description = "Maximum days in advance an appointment can be booked",
                            IsEncrypted = false,
                            SettingKey = "MAX_BOOKING_DAYS_AHEAD",
                            SettingValue = "30"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009001"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9838),
                            Description = "Minimum training hours for Category A (Motorcycle)",
                            IsEncrypted = false,
                            SettingKey = "MIN_TRAINING_HOURS_CATEGORY_A",
                            SettingValue = "8"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009002"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9842),
                            Description = "Minimum training hours for Category B (Private)",
                            IsEncrypted = false,
                            SettingKey = "MIN_TRAINING_HOURS_CATEGORY_B",
                            SettingValue = "20"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009003"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9845),
                            Description = "Minimum training hours for Category C (Public Transport)",
                            IsEncrypted = false,
                            SettingKey = "MIN_TRAINING_HOURS_CATEGORY_C",
                            SettingValue = "30"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009004"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9847),
                            Description = "Minimum training hours for Category D (Heavy Vehicles)",
                            IsEncrypted = false,
                            SettingKey = "MIN_TRAINING_HOURS_CATEGORY_D",
                            SettingValue = "40"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009005"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9850),
                            Description = "Minimum training hours for Category E (Industrial)",
                            IsEncrypted = false,
                            SettingKey = "MIN_TRAINING_HOURS_CATEGORY_E",
                            SettingValue = "40"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009006"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9853),
                            Description = "Minimum training hours for Category F (Agricultural)",
                            IsEncrypted = false,
                            SettingKey = "MIN_TRAINING_HOURS_CATEGORY_F",
                            SettingValue = "20"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000009007"),
                            Category = "Training",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9868),
                            Description = "Minimum age for Category F (Agricultural)",
                            IsEncrypted = false,
                            SettingKey = "MIN_AGE_CATEGORY_F",
                            SettingValue = "18"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010002"),
                            Category = "Theory",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9894),
                            Description = "Number of theory test questions for Category F (Agricultural)",
                            IsEncrypted = false,
                            SettingKey = "THEORY_QUESTIONS_CATEGORY_F",
                            SettingValue = "20"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000011004"),
                            Category = "License",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9897),
                            Description = "License validity in years for Category F (Agricultural)",
                            IsEncrypted = false,
                            SettingKey = "VALIDITY_YEARS_CATEGORY_F",
                            SettingValue = "10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010001"),
                            Category = "Theory",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9901),
                            Description = "Minimum passing score for theory test",
                            IsEncrypted = false,
                            SettingKey = "MIN_PASS_SCORE_THEORY",
                            SettingValue = "80"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000011001"),
                            Category = "Practical",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9904),
                            Description = "Minimum passing score for practical test",
                            IsEncrypted = false,
                            SettingKey = "MIN_PASS_SCORE_PRACTICAL",
                            SettingValue = "80"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000011002"),
                            Category = "Practical",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9906),
                            Description = "Maximum number of practical test attempts",
                            IsEncrypted = false,
                            SettingKey = "MAX_PRACTICAL_ATTEMPTS",
                            SettingValue = "3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000011003"),
                            Category = "Practical",
                            CreatedAt = new DateTime(2026, 4, 10, 14, 19, 15, 899, DateTimeKind.Utc).AddTicks(9909),
                            Description = "Days applicant must wait before rebooking after practical test failure",
                            IsEncrypted = false,
                            SettingKey = "COOLING_PERIOD_DAYS_PRACTICAL",
                            SettingValue = "7"
                        });
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.TheoryTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConductedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExaminerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PassingScore")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ExaminerId");

                    b.HasIndex("Result");

                    b.ToTable("TheoryTests", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.TrainingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CenterName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExemptionApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExemptionApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExemptionDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExemptionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExemptionRejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExempted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalHoursRequired")
                        .HasColumnType("int");

                    b.Property<string>("TrainerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExemptionApprovedBy");

                    b.HasIndex("ExemptionDocumentId");

                    b.HasIndex("SchoolName");

                    b.HasIndex("TrainingStatus");

                    b.ToTable("TrainingRecords", (string)null);
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("AppRole")
                        .HasColumnType("int");

                    b.Property<string>("ApplicantType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnableEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnablePush")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EnableSms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullNameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecurityBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NotificationPreferences")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PhoneVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegistrationMethod")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<bool>("RequiresPasswordReset")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_NationalId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_PhoneNumber");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Contact", "(Email IS NOT NULL OR PhoneNumber IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Application", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.LicenseCategory", null)
                        .WithMany()
                        .HasForeignKey("LicenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.LicenseCategory", "LicenseCategory")
                        .WithMany()
                        .HasForeignKey("LicenseCategoryId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("LicenseCategory");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.ApplicationDocument", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.ApplicationStatusHistory", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.CategoryUpgrade", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.FeeStructure", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.LicenseCategory", "LicenseCategory")
                        .WithMany()
                        .HasForeignKey("LicenseCategoryId");

                    b.Navigation("LicenseCategory");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.License", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.User", "Holder")
                        .WithMany()
                        .HasForeignKey("HolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.LicenseCategory", "LicenseCategory")
                        .WithMany()
                        .HasForeignKey("LicenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holder");

                    b.Navigation("LicenseCategory");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.LicenseRenewal", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.LicenseReplacement", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.MedicalExamination", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.PracticalTest", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany("PracticalTests")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Examiner");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.PushToken", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.SmsLog", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mojaz.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.TheoryTest", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany("TheoryTests")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Examiner");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.TrainingRecord", b =>
                {
                    b.HasOne("Mojaz.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mojaz.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mojaz.Domain.Entities.User", "ExemptionApprover")
                        .WithMany()
                        .HasForeignKey("ExemptionApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mojaz.Domain.Entities.ApplicationDocument", "ExemptionDocument")
                        .WithMany()
                        .HasForeignKey("ExemptionDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("Creator");

                    b.Navigation("ExemptionApprover");

                    b.Navigation("ExemptionDocument");
                });

            modelBuilder.Entity("Mojaz.Domain.Entities.Application", b =>
                {
                    b.Navigation("PracticalTests");

                    b.Navigation("StatusHistory");

                    b.Navigation("TheoryTests");
                });
#pragma warning restore 612, 618
        }
    }
}
