-- Add missing columns to Users table
USE MojazDb;

-- Check if columns exist before adding
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'AppRole')
BEGIN
    ALTER TABLE Users ADD AppRole tinyint NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'AppointmentPreference')
BEGIN
    ALTER TABLE Users ADD AppointmentPreference nvarchar(10) NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'EnableEmail')
BEGIN
    ALTER TABLE Users ADD EnableEmail bit NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'EnablePush')
BEGIN
    ALTER TABLE Users ADD EnablePush bit NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'EnableSms')
BEGIN
    ALTER TABLE Users ADD EnableSms bit NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'IsSecurityBlocked')
BEGIN
    ALTER TABLE Users ADD IsSecurityBlocked bit NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'RequiresPasswordReset')
BEGIN
    ALTER TABLE Users ADD RequiresPasswordReset bit NULL;
END
GO

PRINT 'Migration completed successfully';