-- Add missing columns to Appointments table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Appointments' AND COLUMN_NAME = 'CheckInTime')
BEGIN
    ALTER TABLE Appointments ADD CheckInTime time NULL;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Appointments' AND COLUMN_NAME = 'ReminderSent')
BEGIN
    ALTER TABLE Appointments ADD ReminderSent bit NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Appointments' AND COLUMN_NAME = 'RescheduleCount')
BEGIN
    ALTER TABLE Appointments ADD RescheduleCount int NULL DEFAULT 0;
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Appointments' AND COLUMN_NAME = 'RowVersion')
BEGIN
    ALTER TABLE Appointments ADD RowVersion rowversion NULL;
END
GO